"""initial-migration

Revision ID: 809fb3ec0567
Revises: 
Create Date: 2021-11-08 13:48:41.009765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809fb3ec0567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=124), nullable=False),
    sa.Column('last_name', sa.String(length=124), nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('country', sa.String(length=124), nullable=False),
    sa.Column('city', sa.String(length=124), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=124), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=False),
    sa.Column('security_number', sa.Integer(), nullable=False),
    sa.Column('card_date', sa.String(length=124), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=124), nullable=False),
    sa.Column('subcategory', sa.String(length=124), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=124), nullable=False),
    sa.Column('last_name', sa.String(length=124), nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('password_hash', sa.String(length=164), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
